apiVersion: v1
kind: Service
metadata:
  name: coral-reef-monitoring
spec:
  selector:
    app: coral-reef-monitoring
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer

